const image_url =
  "https://upload.wikimedia.org/wikipedia/commons/c/c2/Glorious-blue-mountain-range.jpg";

export const episodeData = [
  {
    id: 0,
    title: "Movie#1",
    releaseDate: "2022-09-03",
    image_url: image_url,
    characters: [
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#50" },
    ],
  },
  {
    id: 1,
    title: "Movie#2",
    releaseDate: "2022-09-01",
    image_url: image_url,
    characters: [
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#50" },
    ],
  },
  {
    id: 2,
    title: "Movie#3",
    releaseDate: "2000-09-03",
    image_url: image_url,
    characters: [
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#50" },
    ],
  },
  {
    id: 3,
    title: "Movie#4",
    releaseDate: "2022-06-03",
    image_url: image_url,
    characters: [
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#50" },
    ],
  },
  {
    id: 4,
    title: "Movie#5",
    releaseDate: "2020-09-03",
    image_url: image_url,
    characters: [
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#50" },
    ],
  },
  {
    id: 5,
    title: "Movie#6",
    releaseDate: "2000-09-03",
    image_url: image_url,
    characters: [
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#5" },
      { name: "Character#1" },
      { name: "Character#2" },
      { name: "Character#3" },
      { name: "Character#4" },
      { name: "Character#50" },
    ],
  },
];
